services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: /run/secrets/postgres_password
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
  postgres_password:
    file: ./.secrets/postgres_password